### PR TITLE
Added database upgrade script

### PR DESCRIPTION
**Pull request by chordtoll**
The upgrade-database.py script checks for database changes, and upgrades the database if necessary.

I don't know how many people would use this, but if you think it is helpful, I can write new version definitions and upgrade scripts whenever the database changes.

I am also able to help with new features if you want help.

### CODE REVIEW

**Comment by devdri** [comment]
The script looks fine, will definitely be useful. I can surely add version to db and probably even auto upgrading from the main gui.

I appreciate your enthusiasm, I don't have as much time as I'd want to work on this project, so some help will be great.

If you have some ideas for new features, go ahead. We can also discuss them if you want to or if you have any questions about existing code. Some of it is about 4 years old and really makes me cringe, sorry about that.

Some improvements I'd like to have:
- I see you're using blue.gb - I remember there were some parts in this game that didn't analyze very nicely. You could investigate that.
- Lots of small procedures. Currently a procedure is defined as a contiguous area of code with single entry point. There are some problems: often similar procs are optimized to share an epilog, which results in a tail-call to the epilog. Also, large amounts of small procedures are heavy on graphviz. We need an idea how to handle this mess and make graphs that are actually useful.
- Database becomes slow when filled with 2000 procs. Obviously an index is needed, but I never had spare time to add it.
- Improve the way procedures are represented in database. The basic-blocks (jumps only to start of basic block, never inside) could be added to db and code/data references could have the originating instruction as source address. And procedures could sit on top of that, owning a group of basic-blocks. There are however lots of troubles with this approach. Anyway, a smart new way of storing the graph with more correctness guarantees (no unnecessary procedure splits, no orphans) would be great to have.

Currently I'm working on implementing a feature I had in my head for a long time: support for temporary single-assignment fake registers (in context.py). I didn't want to go with the classic static single assignment form as used in compilers, because it would be unreadable for human. This new feature is going to be something in the middle: between unchanged Z80 registers and SSA form: using original registers where possible, but creating additional variables where registers are not enough. I hope it will help analyze loops, stack usage and other tricky areas, which also makes it possible to recover memcpy and array indexing.

**Comment by chordtoll** [comment]
- What are the issues you see with the basic-blocks approach? I see a few, but want to make sure I am not missing any I could find later.
- Some of the strangeness in Blue is caused by procedures such as Bankswitch:

``` nasm
0000:35D6   A = [H_ROMBank]
0000:35D8   PUSH    AF
0000:35D9   A = B
0000:35DA   [H_ROMBank] = A
0000:35DC   [0000:2000] = A
0000:35DF   BC = 0x35e4
0000:35E2   PUSH    BC
0000:35E3   JP    HL
0000:35E4   POP    BC
0000:35E5   A = B
0000:35E6   [H_ROMBank] = A
0000:35E8   [0000:2000] = A
0000:35EB   RET  
```

Which calls the procedure at 00BB:HHLL.

There is also Predef, that calls a procedure from a table based on the value of A.

There are about 300-ish calls to Bankswitch, which creates a ton of clutter when making graphs.

These procedures obscure the destination of a call. It would be useful to tag all calls to Bankswitch or Predef with the real destination of the call.

This is also a good example of a strange usage of the stack. Instead of using the CALL instruction (none exists for target HL), they push the address 35E4 and use a jump. When RET is used, it POPs the value 35E4, and returns there. It is not possible to detect this automatically, but seeing a literal PUSH followed by a JP may be a sign that this is happening.

I am using https://github.com/iimarckus/pokered/ for reference on most of the procedures.

**Comment by chordtoll** [comment]
Also, is this the best way to communicate with you, or should I use email?

**Comment by devdri** [comment]
Hi,
Both Github and email are ok and I get instant notifications, so whichever you prefer.

The basic blocks: they are used internally during analysis of a single procedure, but I fear some issues when making them exist in the db.
Today, analysing a procedure consists of several parts:
- the procedure is given an entry point and a limit (for example it must end before another proc entry point)
- DFS from the entry point, following simple jumps within limit. If there is a switch, use also its targets, but prefer using normal jumps. This makes sure that the inline jumptable size is detected properly, because there is usually a block of code just next to the jumptable
- look for gaps and shrink the limit, so that procedure is a contiguous block
- a graph of the basic blocks and jumps is given to 'flow analysis'
- flow analysis finds cycles and stuff, converts them to whiles and ifs, the gotos are used only when there is no other way and even in that case they only go forward
- with whiles and other highlevel constructs in place, a next type of analysis is performed
- a 'context' is sliding over the instructions from top to bottom. It is filled with known values of registers, and those values are used by following instructions. For example XOR A,A; LD [FF10],A becomes LD A, 0; LD [FF10], 0. When there is a loop or an if, the context is either invalidated or split or whatever is appropriate.
- now there is a pass going backwards, checking the dependencies of instructions on one another. For example LD A, 0; LD [FF10], 0 becomes just LD [FF10], 0 if A is never used again. This also tells us which registers the procedure uses as arguments and where it stores its result.
- now that we have this highlevel understanding, we get two things: calls and jumps to previously ambiguous addresses are now known - so we update the list of procedure calls. The ins and outs of procedure are known, so when analysing a parent procedure we can say more about register usage and possibly this results in a better analysis of the parent procedure.

Ok, this became long. But how can storing basic blocks in db be problematic?
One problem I see is when there's already a procedure and then we discover a call into the middle (perfectly normal, it's just two procedures with a nop tail-call). With the existing approach everything will be refreshed the next time the first procedure is analyzed. If the procedure owns preanalyzed basic blocks, it might be needed to force it to invalidate those. Also when doing the DFS phase, we should erase old blocks, but still kind of keep track of where there is an external jump marking a split (which is also where the procedure should probably end), but it might be hard to find which jumps come from the old analysis of this procedure and which come from other procedures.
It's definitely doable (and I think will it replace ProcedureRangeAnalysis and change ProcedureGraph a bit), but we need to make sure to properly clean up everything before subsequent analyses.

The far call:
It is always better to have the general analysis sort out and detect such things, but until then we need to hardcode it. This is exactly like inline switch in Zelda games. A RST 0 becomes a switch with jumptable at the next PC. We could either have a setting for it or detect this procedure automatically.
So a Call instruction to Bankswitch should become a Call B:HL.
There are more such procedures and once the analysis engine gets better and understands stack more, we could kind of inline them and let optimizations do the rest (in this case compact them back to Call B:HL).
It looks like Predef contains a different pattern for a switch, it could either be somehow matched, or a temporary override to produce a switch is needed. Again, it would be ideal to have everything automatic, but a config is also acceptable for now.

I have my exams the following days and lots of other stuff piled up, so I won't be updating that often. I'll try to have the better context analysis however and see if it resolves some of the funky stack usage.

**Comment by devdri** [comment]
Also, commit 'Config fixes, fixed broken database-upgrade' breaks stuff. It looks like it reverts previous fix which used filenames instead of connection. I get exception on connecting using another connection as filename.
Should it use filenames or should dbv and dbu accept a connection?

**Pull request merged**
